apiVersion: apps/v1
kind: Deployment
metadata:
  name: goof
  labels:
    app: goof
spec:
  selector: 
    matchLabels:
      app: goof
  replicas: 1 
  template:
    metadata:
      labels: 
        app: goof
    spec:
      containers:
      - image: 730606171750.dkr.ecr.ap-southeast-2.amazonaws.com/vuln-node:latest 
        imagePullPolicy: Always
        name: goof
        ports:
        - containerPort: 4000
        securityContext:
           allowPrivilegeEscalation: true
           runAsNonRoot : false
        env:
           - name: MONGO_HOST
             value: "ec2-13-55-31-203.ap-southeast-2.compute.amazonaws.com"
           - name: MONGO_PORT
             value: "27017"
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
      volumes:
      - name: cache-volume
        emptyDir:
          sizeLimit: 50Gi

---
apiVersion: v1
kind: Service
metadata:
  name: goofservice
  labels:
    app: goof
spec:
  ports:
   - port: 4000
     targetPort: 4000
  selector:
    app: goof
  type: LoadBalancer
