apiVersion: apps/v1
kind: Deployment
metadata:
  name: goof
  labels:
    app: goof
spec:
  selector: 
    matchLabels:
      app: goof
  replicas: 1 
  template:
    metadata:
      labels: 
        app: goof
    spec:
      containers:
      - image: michaelbraunbass/vulnnodeapp:main
        imagePullPolicy: Always
        name: goof
        ports:
        - containerPort: 4000
        securityContext:
           allowPrivilegeEscalation: true
        env:
           - name: MONGO_HOST
             value: "mongo"           
           - name: MONGO_PORT
             value: "27017"


---
apiVersion: v1
kind: Service
metadata:
  name: goofservice
  labels:
    app: goof
spec:
  ports:
   - port: 4000
     targetPort: 4000
  selector:
    app: goof
  type: LoadBalancer
